-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
local set = vim.keymap.set

-- xremapが使えないので苦肉の策
set("n", "<D-a>", "<C-a>")
set("n", "<D-b>", "<C-b>")
set("n", "<D-c>", "<C-c>")
set("n", "<D-d>", "<C-d>")
set("n", "<D-e>", "<C-e>")
set("n", "<D-f>", "<C-f>")
set("n", "<D-g>", "<C-g>")
set("n", "<D-h>", "<C-h>")
set("n", "<D-i>", "<C-i>")
set("n", "<D-j>", "<C-j>")
set("n", "<D-k>", "<C-k>")
set("n", "<D-l>", "<C-l>")
set("n", "<D-m>", "<C-m>")
set("n", "<D-n>", "<C-n>")
set("n", "<D-o>", "<C-o>")
set("n", "<D-p>", "<C-p>")
set("n", "<D-q>", "<C-q>")
set("n", "<D-r>", "<C-r>")
set("n", "<D-s>", "<C-s>")
set("n", "<D-t>", "<C-t>")
set("n", "<D-u>", "<C-u>")
set("n", "<D-v>", "<C-v>")
set("n", "<D-w>", "<C-w>")
set("n", "<D-x>", "<C-x>")
set("n", "<D-y>", "<C-y>")
set("n", "<D-z>", "<C-z>")

set("i", "<D-a>", "<C-a>")
set("i", "<D-b>", "<C-b>")
set("i", "<D-c>", "<C-c>")
set("i", "<D-d>", "<C-d>")
set("i", "<D-e>", "<C-e>")
set("i", "<D-f>", "<C-f>")
set("i", "<D-g>", "<C-g>")
set("i", "<D-h>", "<C-h>")
set("i", "<D-i>", "<C-i>")
set("i", "<D-j>", "<C-j>")
set("i", "<D-k>", "<C-k>")
set("i", "<D-l>", "<C-l>")
set("i", "<D-m>", "<C-m>")
set("i", "<D-n>", "<C-n>")
set("i", "<D-o>", "<C-o>")
set("i", "<D-p>", "<C-p>")
set("i", "<D-q>", "<C-q>")
set("i", "<D-r>", "<C-r>")
set("i", "<D-s>", "<C-s>")
set("i", "<D-t>", "<C-t>")
set("i", "<D-u>", "<C-u>")
set("i", "<D-v>", "<C-v>")
set("i", "<D-w>", "<C-w>")
set("i", "<D-x>", "<C-x>")
set("i", "<D-y>", "<C-y>")
set("i", "<D-z>", "<C-z>")

set("v", "<D-a>", "<C-a>")
set("v", "<D-b>", "<C-b>")
set("v", "<D-c>", "<C-c>")
set("v", "<D-d>", "<C-d>")
set("v", "<D-e>", "<C-e>")
set("v", "<D-f>", "<C-f>")
set("v", "<D-g>", "<C-g>")
set("v", "<D-h>", "<C-h>")
set("v", "<D-i>", "<C-i>")
set("v", "<D-j>", "<C-j>")
set("v", "<D-k>", "<C-k>")
set("v", "<D-l>", "<C-l>")
set("v", "<D-m>", "<C-m>")
set("v", "<D-n>", "<C-n>")
set("v", "<D-o>", "<C-o>")
set("v", "<D-p>", "<C-p>")
set("v", "<D-q>", "<C-q>")
set("v", "<D-r>", "<C-r>")
set("v", "<D-s>", "<C-s>")
set("v", "<D-t>", "<C-t>")
set("v", "<D-u>", "<C-u>")
set("v", "<D-v>", "<C-v>")
set("v", "<D-w>", "<C-w>")
set("v", "<D-x>", "<C-x>")
set("v", "<D-y>", "<C-y>")
set("v", "<D-z>", "<C-z>")
